// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadPassword(arg1) {
  return window['go']['main']['App']['ReadPassword'](arg1);
}
